version: '3.8'

services:
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/nginx/production.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend

  # This is the application backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
    env_file:
      - ./backend/config/.env
    depends_on:
      - mongo

  # This is the database
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

  # This service handles SSL certificates
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.flipbase.dk
    env_file: ./backend/config/.env # Assuming MAIL_USER and MAIL_PASS are here
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./data/mailserver/maildata:/var/mail
      - ./data/mailserver/mailstate:/var/mail-state
      - ./data/mailserver/config/:/tmp/docker-mailserver/
      - ./certbot/conf:/etc/letsencrypt:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_POSTGREY=1
      - ENABLE_SASLAUTHD=1
      - ONE_DIR=1
      - DMS_DEBUG=0
      - SSL_TYPE=letsencrypt
      - SSL_CERT_PATH=/etc/letsencrypt/live/flipbase.dk/fullchain.pem
      - SSL_KEY_PATH=/etc/letsencrypt/live/flipbase.dk/privkey.pem
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    depends_on:
      - backend

  rainloop:
    image: youtous/rainloop
    container_name: rainloop
    restart: always
    volumes:
      - ./data/rainloop:/rainloop/data
    depends_on:
      - mailserver

volumes:
  mongo_data: 