services:
  # Frontend Static Site
  - type: web
    name: flipbase-frontend
    env: static
    buildCommand: cd frontend && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://flipbase-backend.onrender.com

  # Backend API
  - type: web
    name: flipbase-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: flipbase-mongodb
    databaseName: flipbase
    user: flipbase
